type ExperienceModel = {
  display: boolean;
  role: string;
  company: string;
  link: string;
  dates: string;
  description: string;
  descriptions: string[];
  technologies: string[];
  projects?: {
    title: string;
    link: string;
  }[];
};

const experience: ExperienceModel[] = [
  {
    display: true,
    role: 'Co-Founder & CTO',
    company: 'Wavelink',
    link: 'https://wavelink.co',
    dates: 'Jan 2026 - Present',
    description:
      'Build AI-Powered Operating System where creators grow, brands win, and campaigns run themselves. Leading the technical vision and product development.',
    descriptions: [],
    technologies: [
      'Node.js',
      'LLM',
      'AWS Services',
      'RAG',
      'VectorDB',
      'NestJS',
      'LangChain',
      'BullMQ',
      'Redis',
      'Postgres',
      'Docker',
      'Kubernetes',
    ],
    projects: [
      {
        title: 'Join now',
        link: 'https://app.wavelink.co',
      },
    ],
  },
  {
    display: true,
    role: 'Software Engineer',
    company: 'Atlas Financial',
    link: 'https://atlas.financial',
    dates: 'Jul 2023 - Dec 2025',
    description:
      'Led migration from a legacy codebase to a modern stack and reduced overall platform latency by 40%. Introduced AWS CDK to manage infrastructure as code, improving CI/CD rollout speed by 60%.',
    descriptions: [],
    technologies: [
      'React',
      'Next.js',
      'Redux',
      'TypeScript',
      'MUI',
      'Tanstack',
      'Vite',
      'Java',
      'Spring Boot',
      'Postgres',
      'AWS',
      'SQS',
      'SNS',
      'RDS',
      'ECS',
      'S3',
      'DynamoDB',
      'Lambda',
      'Jest',
    ],
    projects: [],
  },
  {
    display: true,
    role: 'Senior Software Engineer',
    company: 'Orsay AI',
    link: 'https://orsay.ai',
    dates: 'Jan 2024 - May 2024',
    description:
      'Built AI agents to unify lead interactions across Instagram, WhatsApp, and Slack, enabling automated, human-like conversations from a single dashboard. Designed dynamic prompt workflows using LangChain and OpenAI with RAG, and implemented features like multi-turn memory and persona switching. Helped grow the platform from 0 to $20k MRR.',
    descriptions: [],
    technologies: [
      'Python',
      'FastAPI',
      'AWS',
      'DynamoDB',
      'S3',
      'Lambda',
      'API Gateway',
      'CloudFront',
      'CDK',
      'Fargate',
      'Grafana faro',
      'Socket.io',
      'React',
      'Tanstack Libaries',
      'TypeScript',
      'Framer Motion',
      'Typescript',
      'Zustand',
      'Shadcn',
    ],
    projects: [],
  },
  {
    display: true,
    role: 'Software Engineer',
    company: 'HIVED',
    link: 'https://hived.space',
    dates: 'Jan 2023 - Jul 2023',
    description:
      'Built the internal warehouse sortation app used daily to manage parcel loading across delivery vehicles. Implemented features like parcel tracking, driver management, and warehouse management to improve efficiency and accuracy.',
    descriptions: [
      'Lead frontend development at HIVED',
      'Create and implement solutions for a variety of microservices used by HIVED',
      'Create applications used by around 20,000 customers daily',
      'Create in-house apps used by our drivers and staff',
    ],
    technologies: [
      'Next.js',
      'React',
      'Redux',
      'Tailwind',
      'Flutter',
      'TypeScript',
      'Go',
      'Fiber',
      'Postgres',
      'MongoDB',
      'S3',
      'Lambda',
      'CloudFront',
      'API Gateway',
      'SQS',
      'SNS',
      'ECS',
      'AWS Services',
    ],
    projects: [
      {
        title: 'Tracking Page',
        link: 'https://track.hived.space',
      },
    ],
  },
  {
    display: false,
    role: 'Software Engineer',
    company: 'University of Exeter',
    link: 'https://www.exeter.ac.uk/',
    dates: 'Jan 2022 - Jan 2023',
    description:
      'Work on a variety of microservices used within the university. Work with Flutter for mobile apps and React for web apps.',
    descriptions: [],
    technologies: [
      'Lambda',
      'Step Functions',
      'S3',
      'Serverless',
      'CloudFront',
      'API Gateway',
      'SQS',
      'SNS',
      'Grafana',
      'Node.js',
      'Postgres',
      'TypeScript',
      'AWS',
      'DynamoDB',
      'Cognito',
      'CDK',
      'Flutter',
      'React',
      'Storybook',
      'Playwright',
    ],
    projects: [
      {
        title: 'Student App',
        link: 'https://m.exeter.ac.uk',
      },
    ],
  },
  {
    display: false,
    role: 'Backend Engineer',
    company: 'European Space Agency (ESA)',
    link: 'https://www.esa.int/',
    dates: 'Jun 2021 - Jan 2022',
    description:
      "Build interactive virtual tour software for ESA's New Norcia Ground Station in Australia to help ESA staff visualise and operate the site remotely from Europe.",
    descriptions: [],
    technologies: [
      'Python',
      'FastAPI',
      'AWS',
      'Fargate',
      'Route53',
      'DynamoDB',
      'IAM',
      'TypeScript',
      'CDK',
      'Postgres',
      'Docker',
      'SQS',
      'SNS',
      'RDS',
      'ECS',
      'S3',
      'CloudFront',
      'Lambda',
      'API Gateway',
      'Terraform',
    ],
    projects: [],
  },
  {
    display: false,
    role: 'Software Engineer',
    company: 'Hatless Studios',
    link: 'https://www.linkedin.com/company/hatless-studios',
    dates: 'Oct 2019 - Jun 2021',
    description: `Work on a variety of projects on both frontend and backend in various industries such as education, health and finance. Worked on inventory management system, student app for university and internal tools and analytics dashboards for agencies.`,
    descriptions: [],
    technologies: [
      'React',
      'Next.js',
      'Redux',
      'Django',
      'Framer motion',
      'TypeScript',
      'Vercel',
      'MongoDB',
      'Gin Gonic',
      'PostgreSQL',
      'AWS Services',
      'Postgres',
      'Docker',
      'Kubernetes',
      'SQS',
      'SNS',
      'RDS',
    ],
  },
];

export { experience };
export type { ExperienceModel };
